function init(self)
	msg.post(".", "acquire_input_focus")
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end


function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action.x and action.y then
		local pos = vmath.vector3(action.x, action.y, 0)
		local world_pos = vmath
		go.set_position(pos)
	end
end