function init(self)
	msg.post(".", "acquire_input_focus")
	self.npc = {}
end

function on_input(self, action_id, action)
	if next(self.npc) and self.npc.is_interactable and mouse_over_npc(self, action.screen_x / 2, action.screen_y / 2) then
		if action_id == hash("touch") and action.pressed then
			msg.post("/projects_gui#projects_gui", self.npc.id)
			self.npc.is_interactable = false
		end

		set_cursor([["url('https://i.postimg.cc/7Zgh6HD5/expression-chat.png'), auto"]])
		
	else
		set_cursor([["url('https://i.postimg.cc/vHVpFDL6/cursor-04.png'), auto"]])
	end
end

function on_message(self, message_id, message)
	if message_id == hash("npc_is_interactable") then
		self.npc.is_interactable = true
	end
	
	if message_id == hash("set_pointer") then
		set_cursor("'pointer'")
	end
	
	if message_id == hash("npc") then
		self.npc = message
	end
end

function mouse_over_npc(self, mouse_x, mouse_y)
	local offset = 9

	return mouse_x > self.npc.position.x - offset
	and mouse_x < self.npc.position.x + offset
	and mouse_y > self.npc.position.y - offset
	and mouse_y < self.npc.position.y + offset
end

function set_cursor(cursor)
	html5.run([[
		if(document.body.style.cursor != ]] .. cursor .. [[){
			document.body.style.cursor = ]] .. cursor .. [[;
		}
	]])
end